version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    hostname: zipkin
    ports:
      - "9411:9411"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    ports:
      - "9093:9093"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    depends_on:
      - alertmanager
    ports:
      - "9090:9090"
    volumes:
      - ../services/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
    volumes:
      - ../services/grafana/provisioning:/etc/grafana/provisioning
      - ../services/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cal
      POSTGRES_USER: cal
      POSTGRES_PASSWORD: cal-secret
    restart: always

  cal:
    image: docker.io/library/cal:1.0.0-SNAPSHOT
    container_name: cal
    hostname: cal
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
      - DB_URL=jdbc:postgresql://postgres:5432/cal
      - DB_USERNAME=cal
      - DB_PASSWORD=cal-secret
    ports:
      - "8080:8080"
    depends_on:
      - postgres
