spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cal
    driverClassName: org.postgresql.Driver
    username: cal
    password: cal-secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: false
